# Cloudflare Tunnel Configuration
#
# After creating your tunnel with: cloudflared tunnel create chq-backend
# Replace <YOUR_TUNNEL_ID> below with your actual tunnel ID
# Replace <YOUR_CREDENTIALS_PATH> with the path shown after tunnel creation

tunnel: <YOUR_TUNNEL_ID>
credentials-file: <YOUR_CREDENTIALS_PATH>

# Ingress rules - routes traffic from Cloudflare to your local backend
ingress:
  # API backend
  - hostname: api.dashboard.codershq.ae
    service: http://localhost:4000

  # Catch-all rule (required)
  - service: http_status:404

# Optional: Enable logging
# loglevel: info

# Optional: Enable metrics
# metrics: localhost:9090
